source 'http://rubygems.org'

gem 'activesupport'
gem 'capybara'
gem 'cucumber'
gem 'faker'
gem 'faye-websocket'
gem 'gmail'
gem 'launchy'
gem 'luhnacy'
gem 'nokogiri'
gem 'poltergeist'
gem 'pry'
gem 'rest-client'
gem 'rspec'
gem 'selenium-webdriver'
gem 'syntax'
gem 'test-unit'